CREATE TABLE MyCategory
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(100) NOT NULL
)

CREATE TABLE MyCountry
(
	[ID] NVARCHAR(100) NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(100) NOT NULL
)

CREATE TABLE MyStore
(
	[CatID] INT NOT NULL, 
    [CouID] NVARCHAR(100) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[Tel] NVARCHAR(100) NOT NULL
)